qowmq/SemiProject

- WebContent/index.css
- WebContent/index.jsp
> index added

- src/DAO/MemberDAO.java
> dao update

- WebContent/adminChallenge/adminChallengeList.jsp
- WebContent/adminChallenge/adminMyPage.jsp
- src/DAO/ChallengeDAO.java
- src/challenge/Servlet/AdminBoardServlet.java
> new thing!

- WebContent/adminChallenge/adminChallengeList.jsp
- WebContent/adminChallenge/writeBoard.jsp
> newnew eger! eger!

- WebContent/giveMain.css
- WebContent/giveMain.jsp
- WebContent/takeMain.css
- WebContent/takeMain.jsp
> giveMain or takeMain second Added

- WebContent/giveMain.jsp
- WebContent/jsp/afterTakeMain.jsp
- WebContent/jsp/userMyPage.jsp
- src/challenge/Servlet/UserBoardServlet.java
> today last

- WebContent/adminChallenge/writeBoard.jsp
- WebContent/jsp/afterTakeMain.jsp
- WebContent/jsp/userMyPage.jsp
- src/DAO/ChallengeDAO.java
- src/DTO/ChallengeDTO.java
- src/challenge/Servlet/AdminBoardServlet.java
- src/challenge/Servlet/UserBoardServlet.java
> today second

- WebContent/jsp/userMyPage.jsp
- src/admin/sever/controller/UserBoardServlet.java
> real Mypage Connect

- WebContent/user/userMyPage.jsp
- build/classes/.gitignore
- src/DAO/ChallengeDAO.java
- src/DTO/ChallengeDTO.java
- src/admin/sever/controller/AdminBoardServlet.java
- src/admin/sever/controller/UserBoardServlet.java
> new user and admin challenge!!

- WebContent/Main/takeMain.jsp
- src/Controller/member.java
- src/admin/sever/controller/UserBoardServlet.java
login logout mypage connection
> login logout mypage connection

- WebContent/Main/donateMain.jsp
> donation main update

- WebContent/Main/donateMain.jsp
- WebContent/Main/takeMain.jsp
- WebContent/user/login/signupcheck.jsp
- src/Controller/member.java
- src/admin/sever/controller/AdminBoardServlet.java
> two main admin add

- WebContent/admin/adminChallengeList.jsp
- WebContent/admin/adminMyPage.jsp
- WebContent/admin/writeBoard.jsp
- WebContent/user/userMyPage.jsp
- src/Controller/member.java
- src/admin/sever/controller/AdminBoardServlet.java
- src/admin/sever/controller/UserBoardServlet.java
> Linked Course

- WebContent/Main/donateMain.jsp
- WebContent/Main/takeMain.jsp
- WebContent/index.jsp
- build/classes/.gitignore
- src/admin/sever/controller/ChallengeServlet.java
sewonkim change jsp or servlet
> sewonkim change jsp or servlet

- WebContent/user/bill.jsp
- WebContent/user/detail.jsp
> detail add

- WebContent/admin/DetailManage.jsp
- WebContent/test.jsp
- src/DAO/ChallengeRecordDAO.java
- src/admin/sever/controller/AdminBoardServlet.java
> board delete complete

- WebContent/Main/donateMain.jsp
- WebContent/Main/takeMain.jsp
> admin page

- WebContent/Main/donateMain.jsp
- WebContent/Main/takeMain.jsp
- WebContent/user/detail.jsp
- WebContent/user/login/logincheck.jsp
- WebContent/user/login/memberlist.jsp
- WebContent/user/login/signup.jsp
- src/Controller/member.java
- src/DAO/MemberDAO.java
> admin login change

- WebContent/user/userMyPage.jsp
- src/DAO/ChallengeDAO.java
- src/DAO/ChallengeRecordDAO.java
- src/admin/sever/controller/UserBoardServlet.java
> userMyPage Modify and connect?

- WebContent/user/detail.jsp
- src/Controller/member.java
- src/admin/sever/controller/UserBoardServlet.java
> detail page update
